---
name: setup-node
description: Setup Environment
inputs:
  node-version:
    description: Version of node (leave empty to infer)
    required: false
  fetch-depth:
    description: Fetch depth passed to git checkout
    required: false

outputs:
  node-version:
    value: ${{ steps.detect-node.outputs.version }}
    description: Detected node version.

runs:
  using: "composite"
  steps:
    - name: Git Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # tag=v4.1.1
      with:
        fetch-depth: ${{ inputs.fetch-depth || 0 }}

    - name: Detect node Version
      id: detect-node
      run: |
        if [[ -z "${{ inputs.node-version }}" ]]; then
          echo "version=$(cat .nvmrc | tr -d '\n')" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.node-version }}" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Set up node ${{ steps.detect-node.outputs.version }}
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65  # tag=v4.0.0
      with:
        node-version: ${{ steps.detect-node.outputs.version }}

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Restore Yarn Cache
      id: yarn-cache
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
      with:
        path: |
          .yarn/cache
          .pnp.*
        key: ${{ runner.os }}-${{ runner.arch }}-${{ steps.detect-node.outputs.version }}-${{ hashFiles('yarn.lock') }}

    - name: Disable Global Cache
      shell: bash
      run: |
        echo "YARN_ENABLE_GLOBAL_CACHE=0" >> "$GITHUB_ENV"

    - name: Install Project
      shell: bash
      run: yarn --immutable
