---
name: setup-node
description: Setup Environment
inputs:
  node-version:
    description: Version of node (leave empty to infer)
    required: false
  fetch-depth:
    description: Fetch depth passed to git checkout
    required: false

outputs:
  node-version:
    value: ${{ steps.detect-node.outputs.version }}
    description: Detected node version.

runs:
  using: "composite"
  steps:
    - name: Git Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: ${{ inputs.fetch-depth || 0 }}

    - name: Detect node Version
      id: detect-node
      run: |
        if [[ -z "${{ inputs.node-version }}" ]]; then
          echo "version=$(cat .nvmrc | tr -d '\n')" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.node-version }}" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Set up node ${{ steps.detect-node.outputs.version }}
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: ${{ steps.detect-node.outputs.version }}

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Restore Yarn Cache
      id: yarn-cache
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: |
          .yarn/cache
          .pnp.*
        key: ${{ runner.os }}-${{ runner.arch }}-${{ steps.detect-node.outputs.version }}-${{ hashFiles('yarn.lock') }}

    - name: Disable Global Cache
      shell: bash
      run: |
        echo "YARN_ENABLE_GLOBAL_CACHE=0" >> "$GITHUB_ENV"

    - name: Install Project
      shell: bash
      run: yarn --immutable
