---
name: setup-terraform
description: Setup Environment
inputs:
  terraform-version:
    description: Version of terraform (leave empty to infer)
    required: false

  fetch-depth:
    description: Fetch depth passed to git checkout
    required: false

  aws-access-key-id:
    description: AWS Access Key ID
    required: false
  aws-secret-access-key:
    description: AWS Secret Access Key
    required: false
  aws-region:
    description: AWS default region
    required: false

outputs:
  terraform-version:
    value: ${{ steps.detect-terraform.outputs.version }}
    description: Detected terraform version.

runs:
  using: "composite"
  steps:
    - name: Git Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: ${{ inputs.fetch-depth || 0 }}

    - name: Detect terraform Version
      id: detect-terraform
      run: |
        if [[ -z "${{ inputs.terraform-version }}" ]]; then
          echo "version=$(cat .tfswitchrc | tr -d '\n')" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.terraform-version }}" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      if: inputs.aws-access-key-id
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region || 'us-east-1' }}

    - name: Set up terraform ${{ steps.detect-terraform.outputs.version }}
      uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
      with:
        terraform_version: ${{ steps.detect-terraform.outputs.version }}
